tupuio/tupuapp

netlify.toml, next.config.js, package-lock.json, package.json, pages/api/auth/[...nextauth].js, pages/auth/signin.js
When deploying on Netlify, the NODE_ENV is no longer set to "development"
but I still want to be able to use the dev login.
Part of #23.
=> Add another way to enable the dev login

netlify.toml, next.config.js
Also removed the next.config.js configuration because it didn't work.
=> Write NEXTAUTH_URL in Netlify via .env.local

README.md, netlify.toml, package-lock.json, package.json, pages/api/profile.js, utils/email/index.js, utils/email/templates/preferences-updated-email.mjml, utils/email/templates/preferences-updated-email.txt
Close #50
1. The SendGrid SDK requires an API key. I am using a test purpose one. Please add one to your `.env.local` file under `SENDGRID_API_KEY`.
2. The SendGrid API works only with verified senders. On your SendGrid account, verify a sender email.
3. Set a `SENDGRID_EMAIL_VERIFIED_SENDER` in `.env.local` with a SendGrid verified sender (for the same API key).
4. Set `DEV_EMAIL_RECIPIENT` in `.env.local` with your email to receive all the emails to your inbox while developing.
5. There are two templates in `utils/email/templates`: they are just a sample, we should create proper templates, everytime we add email sending.
6. To test the feature, go to your [TUPU App preferences](http://localhost:3000/preferences) and edit and save.
Example of your …
=> Sendgrid integration

components/MentorContactMenteeModal/index.js, components/RequestsList/RequestCard.js, components/RequestsList/index.js, pages/api/contactMentee.js, services/index.js
Close #58
- add endpoint contactMentee
- add modal in requests list for each request
- the sending email is not implemented, it will be added later on when PR #53 will be merged
- the endpoint gets correctly the message and the email of mentor and mentee
=> Mentor can contact mentee

components/RequestModal/index.js, components/RequestsList/RequestCard.js, components/RequestsList/index.js, components/TupuAlertDialog/index.js, pages/api/acceptMentorship.js, pages/api/rejectMentorship.js, pages/api/request.js, pages/api/requests.js, services/relationships.js, services/requests.js, types/dbTablesEnums.js, xata/schema.yaml
Close #61 
- accept / reject mentorship
- sits on top of `feat/58-mentor_contact_mentee`
- email notifications depend on PR #53 and PR #51 
---
=> Mentor: accept reject mentorship requests

pages/api/auth/[...nextauth].js, pages/api/mentees/index.js, pages/api/mentors/index.js
Close #75
- Filter test users, add lorenzo dev login credentials
- when this is merged, developers using development env, will see only test users as mentors/mentee
- The app builds and runs properly
=> Filter test users, add lorenzo dev login credentials

pages/api/request.js, pages/api/testNotifications.js
Close #86
- Add mentorship request email notification
- email notifications should be configured, see #50
=> Mentorship request email notification

pages/api/acceptMentorship.js, pages/api/rejectMentorship.js
Close #84
- Stacked on top of branch `feat/64-email-notifications-txt-templates-js-functions` depends on PR #90 .
- Add accept/reject email notification
- email notification should be configured with SendGrid API, see readme
=> Accept/reject mentorship email notification [stack feat/64 - PR #90]

pages/api/contactMentee.js, services/index.js
Close #83 
- Stacked on top of branch `feat/64-email-notifications-txt-templates-js-functions` depends on PR #90 .
- Mentor, contact mentee email notifications
- email notification should be configured with SendGrid API, see readme
=> Mentor, contact mentee email notifications [stack feat/64 - PR #90]

components/ApplicationsList/ApplicationCard.js, components/ApplicationsList/index.js, pages/api/applications.js, pages/api/cancelRequest.js, types/dbTablesEnums.js
Close #65 
Close #85 
- Stacked on top of branch `feat/64-email-notifications-txt-templates-js-functions` depends on PR #90 .
- Applications list is retrieved by status `Pending`
- Mentee cancel mentorship request (`cancelRequest.js` endpoint)
- Email notifications for #85
- email notification should be configured with SendGrid API, see readme
=> Mentee cancel mentorship request [stack feat/64 - PR #90]

.xatarc, package-lock.json, package.json, services/xata.js
And add the region to the Xata URL, which is now needed.
=> Update the xata client

components/RequestModal/index.js
Close #78
- set loading spinner when the mentorship request is being submitted
- load toast notification if the submission of the mentorship request is successful
https://user-images.githubusercontent.com/45630868/207322813-34a0511d-3752-4f5a-8203-12569aee3500.mov
=> feat: add feedback when creating mentorship request

package-lock.json, package.json
Mac OS is affected by lower versions
=> Bump netlify/plugin-nextjs to ^4.30.2

components/MentorContactMenteeModal/index.js, package-lock.json
This relates to issue #77 
Close #77 
- The Send Message button now has a loader when the submission process runs
- There is now a SUCCESS toast that pops up if the message has been successfully sent
=> Contact mentee feedback

components/ApplicationsList/ApplicationCard.js, components/MenteesList/MenteeCard.js, components/MenteesList/index.js, components/MentorshipsList/MentorshipCard.js, components/MentorshipsList/MentorshipInfo.js, components/MentorshipsList/PersonInfo.js, components/MentorshipsList/index.js, components/RequestsList/RequestCard.js, pages/api/closeMentorship.js, pages/api/mentorships.js, pages/api/testNotifications.js, pages/applications.js, pages/mentees/index.js, services/relationships.js, types/dbTablesEnums.js, utils/email/index.js, utils/email/templates/mentee-mentorship-closed-email-mentee.txt, utils/email/templates/mentee-mentorship-closed-email-tupu.txt, utils/email/templates/mentor-mentorship-closed-email-mentor.txt, utils/email/templates/mentor-mentorship-closed-email-tupu.txt
- Close #82 
- Close #69 
- Close #107
- Close #62
- major redesign of `MentorshipCard`, `MenteeCard`, `RequestsCard`, and `ApplicationsCard`
Try all.
=> [82, 69, 107, 62] `MentorshipCard`, `MenteeCard`, `RequestsCard`, and `ApplicationsCard` redesign

components/Sidebar/NavItem.js, components/Sidebar/SidebarContent.js, pages/_app.js, pages/index.js
- Close #79 
- Close #67 
- Close #72 
---
=> [79, 67, 72] Home landing page

pages/api/applicationsCount.js
Close #127
- quick fix for the applications counter
=> Fix applications count

components/ApplicationsList/index.js, components/MenteesList/index.js, components/MentorshipsList/index.js, components/RequestModal/index.js, components/RequestsList/index.js, pages/api/closeMentorship.js
Close #122
- update counters when things change (requests, mentorships, applications, mentees)
=> Update counters properly

components/ApplicationsList/index.js, components/MenteesList/index.js, components/MentorshipsList/index.js, components/RequestModal/index.js, components/RequestsList/index.js, pages/api/closeMentorship.js, pages/api/mentors/index.js
Close #88
- Exclude test users when app is not in dev
=> Exclude test users when app is not in dev

components/MentorsList/index.js, components/RequestModal/index.js, constants/api-constants.js, constants/index.js, pages/api/mentors/index.js, pages/api/request.js
Close #
- prevent more than one request being made to the same mentor
- refresh the mentor list once a request has been made so the requested mentor is removed from the list
- prevent a user from requesting themselves as mentor
- don't return the current user in the mentor list page
=> fix: exclude current user from mentor list

README.md, package-lock.json, package.json
=> chore: update dependencies

auth/index.js, components/Sidebar/SidebarContent.js, constants/api-constants.js, jest.config.mjs, middleware.js, package-lock.json, package.json, pages/api/auth/[...nextauth].js, pages/api/mentors/index.js, pages/api/profile.js, pages/index.js, utils/api/get-user-has-session-and-published.js, utils/api/get-user-has-session-and-published.test.js, utils/email/index.js, utils/email/templates/new-user-created.txt
=> feat: set published flag when adding a new user
